### ISSUE TITLE
Online learning algorithms?

### ISSUE THREAD

**Issue by alonsopg** [nok/sklearn-porter#20]
Which algorithms can be used for streams of data? (e.g. passive aggressive, perceptron )?

**Comment by nok** [comment]
Hello @alonsopg,

for a [incremental learning](http://scikit-learn.org/stable/modules/scaling_strategies.html#incremental-learning) you have to use the `partial_fit` method of [scikit-learn](https://github.com/scikit-learn/scikit-learn) (≠sklearn-porter). The goal of sklearn-porter (this project) is to transpile the final estimator.

Best regards,
Darius
