### ISSUE TITLE
How to port a classifier?

### ISSUE THREAD

**Issue by tomfisher** [nok/sklearn-porter#25]
Hi,

This is a great tool and I've been looking for a while.  

A classifier such as GradientBoostingClassifier is needed, we have to write to you for a feature request.  Actually, I don't mind implementing such one and giving it back to this repo. I checked the document and did not find any article about how to implement a classifier in sklearn.

It would be extremely helpful for this project and other users like me.

Thanks.

**Comment by nok** [comment]
Hello Tom,

[RandomForestClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html) ([example](https://github.com/nok/sklearn-porter/blob/master/examples/estimator/classifier/RandomForestClassifier/java/basics_imported.ipynb)), [ExtraTreesClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesClassifier.html) ([example](https://github.com/nok/sklearn-porter/blob/master/examples/estimator/classifier/ExtraTreesClassifier/java/basics_imported.ipynb)) and the [AdaBoostClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html) ([example](https://github.com/nok/sklearn-porter/blob/master/examples/estimator/classifier/AdaBoostClassifier/java/basics_imported.ipynb)) are similar to the GradientBoostingClassifier. The GradientBoostingClassifier will be supported in the next release I guess.

Darius

**Comment by tomfisher** [comment]
Thanks
