### ISSUE TITLE
Installing using anaconda

### ISSUE THREAD

**Issue by okoutb** [nok/sklearn-porter#32]
Hello
I'm using anaconda3 and I want to install sklearn-porter
What will be the best way to do this?
conda install doesn't work:
```
okoob$ conda install sklearn-porter
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - sklearn-porter

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch
```

**Comment by nok** [comment]
Hello @okoutb, just activate your conda environment and install the package via pip:

```bash
source activate <your_env_name> && pip install sklearn-porter  # \o/
```

If you don't activate a specific conda environment with `source activate <name>` the package will be installed to the default conda environment `root`. You can check your conda environments with `conda list`.

Best,
Darius
