### ISSUE TITLE
Using a nuSVC Model

### ISSUE THREAD

**Issue by knseir** [nok/sklearn-porter#4]
Hi, 
I know sklearn-porter doesn't support nu-SVCs, but those are mathematically equivalent to svm.SVC models (see http://scikit-learn.org/stable/modules/svm.html#nusvc).
I was wondering if there was a workaround for this ?
Thank you

**Comment by nok** [comment]
Hello @knseir,

thanks for the hint. I added the [NuSVC](http://scikit-learn.org/stable/modules/generated/sklearn.svm.NuSVC.html) classifier (\w tests) https://github.com/nok/sklearn-porter/commit/f8dbbf83a4fc9b74e2d1cd5575f4bdf65fd10e95 and pushed it to the [master](https://github.com/nok/sklearn-porter/tree/master) (development) branch. Now by using `pip install https://github.com/nok/sklearn-porter/zipball/master` you can install it locally.

Happy coding,
Darius

**Comment by knseir** [comment]
Hi @nok , Thanks for the update!
Just tried reinstalling the package with pip, it says it's up to date, 
porting the classifier still fails with  `The model is not an instance of a supported classifier or regressor.`

**Comment by nok** [comment]
Yes, you have to remove the current version, try these steps:

```shell
pip uninstall -y sklearn-porter
pip --no-cache-dir install https://github.com/nok/sklearn-porter/zipball/master
```

**Comment by knseir** [comment]
Works perfectly, Thank you !
