### ISSUE TITLE
SVC predict_proba not supported 

### ISSUE THREAD

**Issue by IslamSabdelazez** [nok/sklearn-porter#46]
when i try to export "porter = Porter(model, language='java', method= 'predict_proba')" from SVC model it returns "Currently the chosen model method 'predict_proba' isn't supported." is there any solution to get the probability of the predicted class ?!

**Comment by nok** [comment]
Sorry, not today, this feature is work in progress.

**Comment by lunar74** [comment]
When will you release this feature?  I need this, too.

**Comment by KMKnation** [comment]
Any new updates? on this feature.

**Comment by nok** [comment]
Hello @KMKnation , yes, the adaption of all listed estimators is still in progress.

**Comment by nok** [comment]
The estimator [sklearn.svm.SVC](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC) doesn't support the computation of the class probabilities. There is no `predict_proba` mehtod. Because of that there will be no implementation in `sklearn-porter`.

**Comment by Lyrics1988** [comment]
Hi Nok,

Thanks for the project.

I think sklearn.svm.SVC is supporting class probabilities, as shown in this link:

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC.predict_proba

I wonder if you can include it :-)

**Comment by vizakshat** [comment]
This update is much required please update.

**Comment by AmirHosseinCV** [comment]
I needed the same thing for RandomForestClassifier, I changed the last part of code (in my case, js code):
```
this.predict = function(features) {
        var classes = new Array(3).fill(0);
        for (var i = 0; i < trees.length; i++) {
            classes[trees[i](features)]++;
        }
        return findMax(classes);
}
```
to:
```
this.predict = function(features) {
        var classes = new Array(3).fill(0);
        for (var i = 0; i < trees.length; i++) {
            classes[trees[i](features)]++;
        }
        return classes;
}
```
But I don't know if it works with svm or not.
