### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by Larry-Zheng** [nok/sklearn-porter#55]
Hey guys ， there's a little bug —— "ValueError: ("The classifier doesn't support the given base estimator %s.", None)" .  It seems that the default base estimator for adaboost is DecisionTree but the context code here is "if not isinstance(estimator.base_estimator, DecisionTreeClassifier):". So , please use clf.base_estimator_ (the variable ending with _ is automatically generated by code not given by user ).

**Comment by nok** [comment]
Hello @Larry-Zheng ,

thanks, you're right. This bug is already fixed in the next release (see https://github.com/nok/sklearn-porter/blob/feature/oop-api-refactoring/sklearn_porter/Estimator.py#L136-L145). In general did this bug prevent you to transform your estimator? If so I will push a little patch to the current stable version.

Best,
Darius

**Comment by Larry-Zheng** [comment]
> Hello @Larry-Zheng ,
> 
> thanks, you're right. This bug is already fixed in the next release (see https://github.com/nok/sklearn-porter/blob/feature/oop-api-refactoring/sklearn_porter/Estimator.py#L136-L145). In general did this bug prevent you to transform your estimator? If so I will push a little patch to the current stable version.
> 
> Best,
> Darius

All right, I‘ll update it to the latest version. Thank you ~

**Comment by Larry-Zheng** [comment]
All right， I’ll try it later . Thanks~




------------------ 原始邮件 ------------------
发件人: "Darius Morawiec"<notifications@github.com>;
发送时间: 2019年7月3日(星期三) 凌晨4:14
收件人: "nok/sklearn-porter"<sklearn-porter@noreply.github.com>;
抄送: "bittersweet"<519334736@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [nok/sklearn-porter] A bug (#55)




Hello @Larry-Zheng ,
 
thanks, you're right. This bug is already fixed in the next release (see https://github.com/nok/sklearn-porter/blob/feature/oop-api-refactoring/sklearn_porter/Estimator.py#L136-L145). In general did this bug prevent you to transform your estimator? If so I will push a little patch to the current stable version.
 
Best,
 Darius

**Comment by Larry-Zheng** [comment]
> Hello @Larry-Zheng ,
> 
> thanks, you're right. This bug is already fixed in the next release (see https://github.com/nok/sklearn-porter/blob/feature/oop-api-refactoring/sklearn_porter/Estimator.py#L136-L145). In general did this bug prevent you to transform your estimator? If so I will push a little patch to the current stable version.
> 
> Best,
> Darius
Well , if the base_estimator parameter is declared as DecisionTreeClassifier in Adaboost , the code works fine. And  I'll try the latest release later, thanks ~
