### ISSUE TITLE
Divergence Between Original Model and Ported Model

### ISSUE THREAD

**Issue by JinLi711** [nok/sklearn-porter#57]
I've noticed that the integrity score of the JavaScript ported model for extraTrees is around .86 (after sampling a few thousand random inputs). What would be some possible reasons for the cause of such a large this divergence? The extraTrees have 3 estimators with depth 2.

**Comment by nok** [comment]
Hello @JinLi711,

the algorithm of the prediction and the floating-point precision have an effect.

The accuracy of the prediction will be improved with the next release. The good news is that it's already implemented and commited. But I'm sorry to say that the next release requires more time than I expected. Nevertheless you can copy and paste the relevant parts from the templates directly: [RandomForestClassifier/templates/js/exported.class.jinja2](https://github.com/nok/sklearn-porter/blob/feature/oop-api-refactoring/sklearn_porter/estimator/RandomForestClassifier/templates/js/exported.class.jinja2) 

Don't be confused about the name. The prediction of a RandomForestClassifier and an ExtraTreesClassifier are equal.

Regards,
Darius
