### ISSUE TITLE
Golang SVC

### ISSUE THREAD

**Issue by alext234** [nok/sklearn-porter#61]
I am wondering if it’s possible to add  Golang support for SVM? Seems like Golang support is still limited.

**Comment by nok** [comment]
Yes, it will be in the next major release. And it's already been implemented:
https://github.com/nok/sklearn-porter/tree/release/1.0.0#estimators

If you can't wait, you can install it with:
```bash
pip install scikit-learn==0.21
pip install https://github.com/nok/sklearn-porter/zipball/release/1.0.0
```
But notice that the regression tests failed with the new release of scikit-learn `>= 0.22`. Today I recommend to use scikit-learn `< 0.22` to port support vector machines.

Here is a basic example: https://github.com/nok/sklearn-porter/tree/release/1.0.0#basics
