### ISSUE TITLE
install version 0.7.0+ ERROR

### ISSUE THREAD

**Issue by yhfwww** [nok/sklearn-porter#62]
After executing "PIP install sklearn Porter" in win7 + Python 3.5, I install 7.0 + by default. An error is reported:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in positio
egal multibyte sequence
----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in
aohf\AppData\Local\Temp\pip-install-kzqmrh2h\sklearn-porter\

**Comment by nok** [comment]
I think that it was a small encoding bug in the `setup.py` and it's already been fixed. Did you test the latest stable version `0.7.3`?
```bash
pip install sklearn-porter==0.7.3
```

**Comment by nok** [comment]
In addition I merged and tested a PR related to this issue: https://github.com/nok/sklearn-porter/commit/67f9557f0e1efc86019a21a86b43fcd7c3a3f6a1
