### ISSUE TITLE
RandomForestClassifier export 

### ISSUE THREAD

**Issue by Vasilissk-prog** [nok/sklearn-porter#69]
Hi and thank you very much for your contribution.

I am trying to export a RandomForestClassifier( n_estimators= 100, max_features = 'sqrt',max_depth=100, n_jobs=-1, verbose = 1) , but I think that my laptop runs out of memory. Do you think that I can try in a server with better specifications or only option is to reduce n_estimators and max_depth?

**Comment by nok** [comment]
Hello @Vasilissk-prog ,

yes, either you increase your memory (RAM) resources (e.g. by switching your device) or decrease the number of `n_estimators` and `max_depth`.

Kind regards,
Darius
